name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: logar docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER} } -p ${{ secrets.DOCKER_HUB_PASS } }
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
